
services:
  web:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgresql://postgres:ghhjdjhxghdh4434@172.17.0.1:5432/studyzavr
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5173/api
      - HOSTNAME=0.0.0.0
      - PORT=3005
    volumes:
      - ./files/uploads2345:/app/files/uploads2345
    restart: unless-stopped
