
services:
  web:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgresql://postgres:ghhjdjhxghdh4434@host.docker.internal:5432/studyzavr
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5173/api
      - HOSTNAME=0.0.0.0
      - PORT=3005
    volumes:
      - ./files/uploads2345:/app/files/uploads2345
    restart: unless-stopped
