version: "3.9"
services:
  web:
    build: .
    container_name: studyzavr_web
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: studyzavr_db
    environment:
      POSTGRES_DB: studyzavr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
