
services:
  web:
    build: .
    ports:
      - "3005:3005"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3005
    volumes:
      - ./files/uploads2345:/app/files/uploads2345
    restart: unless-stopped
